/**
 * 汉字识字数据库 - 基于四五快读第一册（扩展版）
 * 总字数：80字（10课，每课8字）
 * 每个汉字包含：拼音、释义、emoji、图片、部首、笔画数、象形字、组词、例句
 */

const chineseData = {
    lesson1: [
        { char: "人", pinyin: "rén", meaning: "人类，能制造工具并使用工具进行劳动的高等动物", emoji: "👤", image: "https://source.unsplash.com/featured/?person,people", radical: "人", strokes: 2, isPictograph: true, pictograph: { origin: "甲骨文", description: "像人的侧面站立形状，有头、身、手、脚", stages: [{ url: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/U30007_u4eba.svg/120px-U30007_u4eba.svg.png", label: "甲骨文" }, { url: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/%E4%BA%BA-seal.svg/120px-%E4%BA%BA-seal.svg.png", label: "小篆" }] }, words: ["人们", "大人", "人口", "人民"], sentences: ["爸爸是大人。", "这里人口很多。", "人们都在工作。"] },
        { char: "口", pinyin: "kǒu", meaning: "人和动物吃东西的器官，也是发音的器官", emoji: "👄", image: "https://source.unsplash.com/featured/?mouth", radical: "口", strokes: 3, isPictograph: true, pictograph: { origin: "甲骨文", description: "像嘴巴张开的形状", stages: [{ url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/U53e3_u53e3.svg/120px-U53e3_u53e3.svg.png", label: "甲骨文" }] }, words: ["人口", "门口", "出口", "入口"], sentences: ["小口张开。", "门口有一棵树。", "这是出口。"] },
        { char: "大", pinyin: "dà", meaning: "在体积、面积、数量、力量等方面超过一般或所比较的对象", emoji: "📏", image: "https://source.unsplash.com/featured/?big,large", radical: "大", strokes: 3, isPictograph: false, words: ["大人", "大小", "大树", "大门"], sentences: ["爸爸是大人。", "大树很高。", "大门开着。"] },
        { char: "中", pinyin: "zhōng", meaning: "和四周距离相等的位置", emoji: "🎯", image: "https://source.unsplash.com/featured/?middle,center", radical: "丨", strokes: 4, isPictograph: false, words: ["中心", "中间", "中国", "中午"], sentences: ["我站在中间。", "这是中心。", "中午吃饭了。"] },
        { char: "小", pinyin: "xiǎo", meaning: "在体积、面积、数量等方面不及一般的或所比较的对象", emoji: "🔬", image: "https://source.unsplash.com/featured/?small,little", radical: "小", strokes: 3, isPictograph: false, words: ["小人", "小鸟", "小手", "小孩"], sentences: ["小鸟在天上飞。", "小手很干净。", "小孩在笑。"] },
        { char: "哭", pinyin: "kū", meaning: "因悲伤或激动而流泪，发出声音", emoji: "😢", image: "https://source.unsplash.com/featured/?crying,sad", radical: "口", strokes: 10, isPictograph: false, words: ["哭泣", "大哭", "哭了"], sentences: ["小弟弟哭了。", "不要大哭。", "她为什么哭？"] },
        { char: "笑", pinyin: "xiào", meaning: "露出愉快的表情，发出欢喜的声音", emoji: "😄", image: "https://source.unsplash.com/featured/?smile,happy", radical: "竹", strokes: 10, isPictograph: false, words: ["大笑", "笑话", "微笑", "笑脸"], sentences: ["大家都在笑。", "笑脸真好看。", "爸爸讲笑话。"] },
        { char: "一", pinyin: "yī", meaning: "数目字，最小的正整数", emoji: "1️⃣", image: "https://source.unsplash.com/featured/?one", radical: "一", strokes: 1, isPictograph: true, pictograph: { origin: "指事字", description: "用一横表示数字一", stages: [] }, words: ["一个", "一天", "一年", "一起"], sentences: ["我有一个苹果。", "一天过去了。", "我们一起去。"] }
    ],
    lesson2: [
        { char: "地", pinyin: "dì", meaning: "地球表面的土壤、陆地", emoji: "🌍", image: "https://source.unsplash.com/featured/?earth,ground", radical: "土", strokes: 6, isPictograph: false, words: ["大地", "土地", "地上", "地球"], sentences: ["地上有小草。", "大地很广。", "地球是圆的。"] },
        { char: "阳", pinyin: "yáng", meaning: "太阳，日光", emoji: "🌞", image: "https://source.unsplash.com/featured/?sunshine", radical: "阝", strokes: 6, isPictograph: false, words: ["太阳", "阳光", "阳台", "阳明"], sentences: ["太阳出来了。", "阳光很温暖。", "阳台上有花。"] },
        { char: "亮", pinyin: "liàng", meaning: "光线充足，明亮", emoji: "💡", image: "https://source.unsplash.com/featured/?bright,light", radical: "亠", strokes: 9, isPictograph: false, words: ["明亮", "天亮", "闪亮", "月亮"], sentences: ["天亮了。", "灯很明亮。", "月亮很亮。"] },
        { char: "星", pinyin: "xīng", meaning: "夜晚天空中闪烁的天体", emoji: "⭐", image: "https://source.unsplash.com/featured/?star,night", radical: "日", strokes: 9, isPictograph: false, words: ["星星", "星光", "明星", "火星"], sentences: ["天上有星星。", "星星在发光。", "明星很亮。"] },
        { char: "云", pinyin: "yún", meaning: "漂浮在空中的水蒸气凝结物", emoji: "☁️", image: "https://source.unsplash.com/featured/?cloud,sky", radical: "二", strokes: 4, isPictograph: true, pictograph: { origin: "象形字", description: "像天空中卷曲的云朵", stages: [{ url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/U4e91_u4e91.svg/120px-U4e91_u4e91.svg.png", label: "甲骨文" }] }, words: ["白云", "云朵", "云彩", "乌云"], sentences: ["天上有白云。", "云朵像棉花。", "乌云来了。"] },
        { char: "火", pinyin: "huǒ", meaning: "物质燃烧时发出的光和热", emoji: "🔥", image: "https://source.unsplash.com/featured/?fire,flame", radical: "火", strokes: 4, isPictograph: true, pictograph: { origin: "象形字", description: "像火焰向上燃烧的样子", stages: [{ url: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/U706b_u706b.svg/120px-U706b_u706b.svg.png", label: "甲骨文" }] }, words: ["大火", "火苗", "火光", "火车"], sentences: ["火很亮。", "大火烧了三天。", "火车开了。"] },
        { char: "水", pinyin: "shuǐ", meaning: "无色无味透明的液体，生命必需", emoji: "💧", image: "https://source.unsplash.com/featured/?water,blue", radical: "水", strokes: 4, isPictograph: true, pictograph: { origin: "象形字", description: "像河流中间的水流，两边是河岸", stages: [{ url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/U6c34_u6c34.svg/120px-U6c34_u6c34.svg.png", label: "甲骨文" }] }, words: ["水果", "河水", "水平", "喝水"], sentences: ["我在喝水。", "水里有鱼。", "河水在流。"] },
        { char: "三", pinyin: "sān", meaning: "数目字，二加一所得", emoji: "3️⃣", image: "https://source.unsplash.com/featured/?three", radical: "一", strokes: 3, isPictograph: true, pictograph: { origin: "指事字", description: "用三横表示数字三", stages: [] }, words: ["三个", "三天", "三年", "三次"], sentences: ["我有三个苹果。", "三天后见。", "他来了三次。"] }
    ],
    lesson3: [
        { char: "土", pinyin: "tǔ", meaning: "地面上的泥沙混合物", emoji: "🏔️", image: "https://source.unsplash.com/featured/?soil,dirt", radical: "土", strokes: 3, isPictograph: true, pictograph: { origin: "象形字", description: "像地面上凸起的一堆土", stages: [{ url: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/U571f_u571f.svg/120px-U571f_u571f.svg.png", label: "甲骨文" }] }, words: ["土地", "泥土", "土豆", "土星"], sentences: ["土里有虫子。", "土地很肥。", "土豆很好吃。"] },
        { char: "山", pinyin: "shān", meaning: "地面上由土石构成的高耸部分", emoji: "⛰️", image: "https://source.unsplash.com/featured/?mountain", radical: "山", strokes: 3, isPictograph: true, pictograph: { origin: "象形字", description: "像连绵起伏的山峰", stages: [{ url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/U5c71_u5c71.svg/120px-U5c71_u5c71.svg.png", label: "甲骨文" }] }, words: ["山上", "大山", "山水", "山羊"], sentences: ["山上有树。", "大山很高。", "山羊在吃草。"] },
        { char: "石", pinyin: "shí", meaning: "构成地壳的矿物质硬块", emoji: "🪨", image: "https://source.unsplash.com/featured/?rock,stone", radical: "石", strokes: 5, isPictograph: true, pictograph: { origin: "象形字", description: "像山崖下的一块石头", stages: [{ url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/U77f3_u77f3.svg/120px-U77f3_u77f3.svg.png", label: "甲骨文" }] }, words: ["石头", "石子", "石板", "宝石"], sentences: ["地上有石头。", "我捡了一个石子。", "宝石很亮。"] },
        { char: "木", pinyin: "mù", meaning: "树木，也指木材", emoji: "🪵", image: "https://source.unsplash.com/featured/?wood,tree", radical: "木", strokes: 4, isPictograph: true, pictograph: { origin: "象形字", description: "像一棵树，有树干、树枝和树根", stages: [{ url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/U6728_u6728.svg/120px-U6728_u6728.svg.png", label: "甲骨文" }] }, words: ["木头", "树木", "木马", "木耳"], sentences: ["木头很硬。", "树木绿了。", "木马在摇。"] },
        { char: "我", pinyin: "wǒ", meaning: "称自己", emoji: "🙋", image: "https://source.unsplash.com/featured/?me,person", radical: "戈", strokes: 7, isPictograph: false, words: ["我们", "我的", "我家", "自我"], sentences: ["我是小孩。", "我的书在这里。", "我们一起去。"] },
        { char: "好", pinyin: "hǎo", meaning: "优点多的，使人满意的", emoji: "👍", image: "https://source.unsplash.com/featured/?good,thumbs", radical: "女", strokes: 6, isPictograph: false, words: ["好人", "好事", "好看", "好朋友"], sentences: ["他是个好人。", "这是一件好事。", "你真好看。"] },
        { char: "有", pinyin: "yǒu", meaning: "表示存在", emoji: "✅", image: "https://source.unsplash.com/featured/?have,exist", radical: "月", strokes: 6, isPictograph: false, words: ["没有", "有的", "有人", "有力"], sentences: ["我有一个苹果。", "水里有很多鱼。", "有人来了。"] },
        { char: "田", pinyin: "tián", meaning: "种植农作物的土地", emoji: "🌾", image: "https://source.unsplash.com/featured/?field,farm", radical: "田", strokes: 5, isPictograph: true, pictograph: { origin: "象形字", description: "像一块块被田埂分开的土地", stages: [{ url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/U7530_u7530.svg/120px-U7530_u7530.svg.png", label: "甲骨文" }] }, words: ["田地", "水田", "田野", "种田"], sentences: ["田里有水。", "水田里有鱼。", "农民在种田。"] }
    ],
    lesson4: [
        { char: "牛", pinyin: "niú", meaning: "一种常见的家畜，能耕田拉车", emoji: "🐄", image: "https://source.unsplash.com/featured/?cow", radical: "牛", strokes: 4, isPictograph: true, pictograph: { origin: "象形字", description: "像牛头正面，有角和耳朵", stages: [{ url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/U725b_u725b.svg/120px-U725b_u725b.svg.png", label: "甲骨文" }] }, words: ["水牛", "牛奶", "牛皮", "老牛"], sentences: ["水牛在吃草。", "牛奶很好喝。", "老牛慢慢走。"] },
        { char: "羊", pinyin: "yáng", meaning: "一种常见的家畜，性情温顺", emoji: "🐑", image: "https://source.unsplash.com/featured/?sheep", radical: "羊", strokes: 6, isPictograph: true, pictograph: { origin: "象形字", description: "像羊头正面，有弯曲的角", stages: [{ url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/U7f8a_u7f8a.svg/120px-U7f8a_u7f8a.svg.png", label: "甲骨文" }] }, words: ["山羊", "绵羊", "小羊", "羊毛"], sentences: ["山羊在山上。", "小羊在吃草。", "羊毛很软。"] },
        { char: "聪", pinyin: "cōng", meaning: "智力发达，听觉灵敏", emoji: "🧠", image: "https://source.unsplash.com/featured/?smart,intelligence", radical: "耳", strokes: 15, isPictograph: false, words: ["聪明", "聪慧", "聪敏"], sentences: ["他是个聪明的孩子。", "聪明的小手会做事。", "这只小狗很聪慧。"] },
        { char: "耳", pinyin: "ěr", meaning: "人和动物的听觉器官", emoji: "👂", image: "https://source.unsplash.com/featured/?ear", radical: "耳", strokes: 6, isPictograph: true, pictograph: { origin: "象形字", description: "像人的耳朵形状", stages: [{ url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/U8033_u8033.svg/120px-U8033_u8033.svg.png", label: "甲骨文" }] }, words: ["耳朵", "耳光", "耳机", "耳闻"], sentences: ["我的耳朵很大。", "山羊的耳朵很长。", "我在听耳机。"] },
        { char: "目", pinyin: "mù", meaning: "眼睛，也作动词表示看", emoji: "👁️", image: "https://source.unsplash.com/featured/?eye", radical: "目", strokes: 5, isPictograph: true, pictograph: { origin: "象形字", description: "像人的眼睛，横着看是眼球的形状", stages: [{ url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/U76ee_u76ee.svg/120px-U76ee_u76ee.svg.png", label: "甲骨文" }] }, words: ["目光", "目标", "目送", "目录"], sentences: ["目光很亮。", "这是我的目标。", "目送小船远去。"] },
        { char: "心", pinyin: "xīn", meaning: "人和动物体内推动血液循环的器官，也指思想感情", emoji: "❤️", image: "https://source.unsplash.com/featured/?heart", radical: "心", strokes: 4, isPictograph: true, pictograph: { origin: "象形字", description: "像心脏的形状", stages: [{ url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/U5fc3_u5fc3.svg/120px-U5fc3_u5fc3.svg.png", label: "甲骨文" }] }, words: ["心里", "开心", "小心", "心中"], sentences: ["我心里很高兴。", "小心一点。", "他在心中想。"] },
        { char: "和", pinyin: "hé", meaning: "连接、并列，也表示关系好", emoji: "🤝", image: "https://source.unsplash.com/featured/?together,and", radical: "禾", strokes: 8, isPictograph: false, words: ["和好", "和平", "温和", "和谐"], sentences: ["我们和好。", "和平很重要。", "天气温和。"] },
        { char: "四", pinyin: "sì", meaning: "数目字，三加一所得", emoji: "4️⃣", image: "https://source.unsplash.com/featured/?four", radical: "囗", strokes: 5, isPictograph: true, pictograph: { origin: "指事字", description: "像四根横线表示数字四", stages: [] }, words: ["四个", "四天", "四年", "四方"], sentences: ["我有四个苹果。", "四天后见。", "四方都是山。"] }
    ],
    lesson5: [
        { char: "明", pinyin: "míng", meaning: "光线充足，清楚可见", emoji: "✨", image: "https://source.unsplash.com/featured/?bright,shine", radical: "日", strokes: 8, isPictograph: false, words: ["明天", "明亮", "明白", "明月"], sentences: ["明天见。", "房间很明亮。", "月亮明又圆。"] },
        { char: "头", pinyin: "tóu", meaning: "人或动物脖子以上的部位", emoji: "🗣️", image: "https://source.unsplash.com/featured/?head", radical: "大", strokes: 5, isPictograph: false, words: ["头发", "头顶", "石头", "舌头"], sentences: ["头发黑了。", "头顶上有天空。", "石头很重。"] },
        { char: "眉", pinyin: "méi", meaning: "眼上额下的毛", emoji: "😏", image: "https://source.unsplash.com/featured/?eyebrow", radical: "目", strokes: 9, isPictograph: false, words: ["眉毛", "眉头", "眉心", "浓眉"], sentences: ["眉毛下面是眼睛。", "他皱起了眉头。", "浓眉毛真好看。"] },
        { char: "鼻", pinyin: "bí", meaning: "人和动物嗅觉和呼吸的器官", emoji: "👃", image: "https://source.unsplash.com/featured/?nose", radical: "鼻", strokes: 14, isPictograph: false, words: ["鼻子", "鼻孔", "鼻尖"], sentences: ["我的鼻子很小。", "鼻孔在呼吸。", "鼻尖红红的。"] },
        { char: "手", pinyin: "shǒu", meaning: "人体上肢前端能拿东西的部分", emoji: "✋", image: "https://source.unsplash.com/featured/?hand", radical: "手", strokes: 4, isPictograph: true, pictograph: { origin: "象形字", description: "像张开的手，有五根手指", stages: [{ url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/U624b_u624b.svg/120px-U624b_u624b.svg.png", label: "甲骨文" }] }, words: ["小手", "手指", "手心", "手里"], sentences: ["我的小手很干净。", "手指真灵活。", "手心里有东西。"] },
        { char: "花", pinyin: "huā", meaning: "种子植物的繁殖器官，有各种颜色和香味", emoji: "🌸", image: "https://source.unsplash.com/featured/?flower", radical: "艹", strokes: 7, isPictograph: false, words: ["花朵", "花园", "开花", "花草"], sentences: ["花园里有很多花。", "花朵很漂亮。", "春天开花。"] },
        { char: "树", pinyin: "shù", meaning: "木本植物，由根、干、枝、叶组成", emoji: "🌳", image: "https://source.unsplash.com/featured/?tree", radical: "木", strokes: 9, isPictograph: false, words: ["大树", "树叶", "树木", "果树"], sentences: ["树上有很多花和叶子。", "大树下很凉快。", "树叶绿了。"] },
        { char: "五", pinyin: "wǔ", meaning: "数目字，四加一所得", emoji: "5️⃣", image: "https://source.unsplash.com/featured/?five", radical: "二", strokes: 4, isPictograph: true, pictograph: { origin: "指事字", description: "古代用五横表示数字五", stages: [] }, words: ["五个", "五天", "五年", "五岁"], sentences: ["我有五个朋友。", "五天后见。", "弟弟五岁了。"] }
    ],
    lesson6: [
        { char: "草", pinyin: "cǎo", meaning: "草本植物，通常指野草", emoji: "🌿", image: "https://source.unsplash.com/featured/?grass", radical: "艹", strokes: 9, isPictograph: true, pictograph: { origin: "象形字", description: "像两棵并排生长的小草", stages: [{ url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/U8349_u8349.svg/120px-U8349_u8349.svg.png", label: "甲骨文" }] }, words: ["草地", "小草", "花草", "青草"], sentences: ["草地很绿。", "小草在生长。", "山羊在吃草。"] },
        { char: "叶", pinyin: "yè", meaning: "植物进行光合作用的主要器官", emoji: "🍃", image: "https://source.unsplash.com/featured/?leaf", radical: "口", strokes: 5, isPictograph: false, words: ["叶子", "树叶", "绿叶", "叶片"], sentences: ["树上的叶子很绿。", "叶子落下来了。", "绿叶在生长。"] },
        { char: "日", pinyin: "rì", meaning: "太阳，也指一天", emoji: "📅", image: "https://source.unsplash.com/featured/?sun,day", radical: "日", strokes: 4, isPictograph: true, pictograph: { origin: "象形字", description: "像圆圆的太阳", stages: [{ url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/U65e5_u65e5.svg/120px-U65e5_u65e5.svg.png", label: "甲骨文" }] }, words: ["日子", "日光", "日出", "日落"], sentences: ["日子一天天过去。", "日光很温暖。", "日出很美。"] },
        { char: "风", pinyin: "fēng", meaning: "空气流动形成的自然现象", emoji: "💨", image: "https://source.unsplash.com/featured/?wind", radical: "风", strokes: 4, isPictograph: true, pictograph: { origin: "象形字", description: "像凤凰展翅，借凤表风", stages: [{ url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/U98ce_u98ce.svg/120px-U98ce_u98ce.svg.png", label: "甲骨文" }] }, words: ["大风", "风景", "风筝", "微风"], sentences: ["大风在吹。", "风景很美。", "风筝飞上天。"] },
        { char: "雨", pinyin: "yǔ", meaning: "从云层中降落到地面的水滴", emoji: "🌧️", image: "https://source.unsplash.com/featured/?rain", radical: "雨", strokes: 8, isPictograph: true, pictograph: { origin: "象形字", description: "像云层下落下雨滴", stages: [{ url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/U96e8_u96e8.svg/120px-U96e8_u96e8.svg.png", label: "甲骨文" }] }, words: ["下雨", "大雨", "雨水", "雨天"], sentences: ["下雨了。", "大雨哗哗下。", "雨水滋润大地。"] },
        { char: "的", pinyin: "de", meaning: "用在定语和中心词之间，表示领属或修饰关系", emoji: "📝", image: "https://source.unsplash.com/featured/?of,belong", radical: "白", strokes: 8, isPictograph: false, words: ["我的", "你的", "红的", "小的"], sentences: ["这是我的书。", "红红的太阳。", "小鸟飞得高。"] },
        { char: "孩", pinyin: "hái", meaning: "儿童，幼童", emoji: "👶", image: "https://source.unsplash.com/featured/?child,kid", radical: "子", strokes: 9, isPictograph: false, words: ["孩子", "小孩", "男孩", "女孩"], sentences: ["孩子笑了。", "小孩在跑步。", "男孩和女孩。"] },
        { char: "六", pinyin: "liù", meaning: "数目字，五加一所得", emoji: "6️⃣", image: "https://source.unsplash.com/featured/?six", radical: "八", strokes: 4, isPictograph: true, pictograph: { origin: "指事字", description: "像房屋侧面的形状，借为数字六", stages: [] }, words: ["六个", "六天", "六年", "六岁"], sentences: ["我有六个苹果。", "六天过去了。", "妹妹六岁了。"] }
    ],
    lesson7: [
        { char: "在", pinyin: "zài", meaning: "表示存在、处于某个地点或时间", emoji: "📍", image: "https://source.unsplash.com/featured/?location,place", radical: "土", strokes: 6, isPictograph: false, words: ["在家", "在学校", "在书上", "在这里"], sentences: ["我在家里。", "妈妈在学校。", "小鸟在树上。"] },
        { char: "是", pinyin: "shì", meaning: "表示肯定、判断或存在", emoji: "✅", image: "https://source.unsplash.com/featured/?yes,check", radical: "日", strokes: 9, isPictograph: false, words: ["是的", "不是", "就是", "但是"], sentences: ["我是小孩。", "这是红色的。", "爸爸是医生。"] },
        { char: "了", pinyin: "le", meaning: "用在动词或形容词后，表示动作或变化已经完成", emoji: "🕐", image: "https://source.unsplash.com/featured/?done,complete", radical: "亅", strokes: 2, isPictograph: false, words: ["好了", "来了", "走了", "笑了"], sentences: ["饭好了。", "爸爸来了。", "太阳出来了。"] },
        { char: "不", pinyin: "bù", meaning: "表示否定", emoji: "❌", image: "https://source.unsplash.com/featured/?no,negative", radical: "一", strokes: 4, isPictograph: false, words: ["不要", "不是", "不好", "不大"], sentences: ["不要跑。", "这不是我的。", "不大不小的。"] },
        { char: "来", pinyin: "lái", meaning: "从别的地方到说话人所在的地方", emoji: "👋", image: "https://source.unsplash.com/featured/?come,arrive", radical: "木", strokes: 7, isPictograph: false, words: ["来了", "过来", "来到", "上来"], sentences: ["妈妈来了。", "快过来。", "汽车开来了。"] },
        { char: "去", pinyin: "qù", meaning: "从说话人所在的地方到别的地方", emoji: "🚶", image: "https://source.unsplash.com/featured/?go,leave", radical: "厶", strokes: 5, isPictograph: false, words: ["去了", "出去", "下去", "去哪里"], sentences: ["爸爸去上班了。", "小鸟飞去了。", "我们出去玩。"] },
        { char: "吗", pinyin: "ma", meaning: "用在句末表示疑问", emoji: "❓", image: "https://source.unsplash.com/featured/?question,ask", radical: "口", strokes: 6, isPictograph: false, words: ["好吗", "是吗", "对吗", "要吗"], sentences: ["你好吗？", "这是你的吗？", "我们出去玩吗？"] },
        { char: "呢", pinyin: "ne", meaning: "用在句末表示疑问或停顿", emoji: "💬", image: "https://source.unsplash.com/featured/?talk,speak", radical: "口", strokes: 8, isPictograph: false, words: ["你呢", "为什么呢", "什么呢"], sentences: ["你好吗？我很好，你呢？", "为什么呢？", "这是什么呢？"] }
    ],
    lesson8: [
        { char: "书", pinyin: "shū", meaning: "装订成册的著作，也泛指书本", emoji: "📚", image: "https://source.unsplash.com/featured/?book,read", radical: "乛", strokes: 4, isPictograph: false, words: ["书本", "读书", "看书", "书包"], sentences: ["我在看书。", "书包里有书。", "这本书很好看。"] },
        { char: "包", pinyin: "bāo", meaning: "用纸、布等把东西裹起来，也指装东西的袋子", emoji: "🎒", image: "https://source.unsplash.com/featured/?bag,backpack", radical: "勹", strokes: 5, isPictograph: false, words: ["书包", "包子", "红包", "背包"], sentences: ["这是我的书包。", "包子很好吃。", "爸爸背着一个包。"] },
        { char: "笔", pinyin: "bǐ", meaning: "用来写字或画画的工具", emoji: "✏️", image: "https://source.unsplash.com/featured/?pen,pencil", radical: "竹", strokes: 10, isPictograph: false, words: ["铅笔", "毛笔", "钢笔", "笔画"], sentences: ["我用铅笔写字。", "这支笔很好。", "毛笔软软的。"] },
        { char: "尺", pinyin: "chǐ", meaning: "测量长度的工具", emoji: "📏", image: "https://source.unsplash.com/featured/?ruler,measure", radical: "尸", strokes: 4, isPictograph: false, words: ["尺子", "直尺", "卷尺", "尺寸"], sentences: ["用尺子量一量。", "直尺是直的。", "这块布有多长？"] },
        { char: "桌", pinyin: "zhuō", meaning: "一种家具，上面可以放东西或写字吃饭", emoji: "🪑", image: "https://source.unsplash.com/featured/?table,desk", radical: "木", strokes: 10, isPictograph: false, words: ["桌子", "书桌", "课桌", "餐桌"], sentences: ["桌子上有书。", "我在书桌前写字。", "课桌里有一支笔。"] },
        { char: "椅", pinyin: "yǐ", meaning: "有靠背的坐具", emoji: "🪑", image: "https://source.unsplash.com/featured/?chair,seat", radical: "木", strokes: 12, isPictograph: false, words: ["椅子", "座椅", "木椅", "躺椅"], sentences: ["椅子上坐着小猫。", "请坐在椅子上。", "这把椅子很结实。"] },
        { char: "门", pinyin: "mén", meaning: "房屋、车船等的出入口", emoji: "🚪", image: "https://source.unsplash.com/featured/?door,gate", radical: "门", strokes: 3, isPictograph: true, pictograph: { origin: "象形字", description: "像两扇门", stages: [{ url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/U95e8_u95e8.svg/120px-U95e8_u95e8.svg.png", label: "甲骨文" }] }, words: ["门口", "开门", "关门", "大门"], sentences: ["门口有一棵树。", "请开门。", "大门关上了。"] },
        { char: "窗", pinyin: "chuāng", meaning: "房屋墙上通气透光的装置", emoji: "🪟", image: "https://source.unsplash.com/featured/?window,glass", radical: "穴", strokes: 12, isPictograph: false, words: ["窗户", "开窗", "玻璃窗", "窗外"], sentences: ["窗户开着。", "窗外有树。", "打开窗户透气。"] }
    ],
    lesson9: [
        { char: "前", pinyin: "qián", meaning: "人面所向的一面，空间或位置在正面的", emoji: "➡️", image: "https://source.unsplash.com/featured/?front,before", radical: "刂", strokes: 9, isPictograph: false, words: ["前面", "前后", "前进", "以前"], sentences: ["我在你的前面。", "前后都有人。", "汽车向前开。"] },
        { char: "后", pinyin: "hòu", meaning: "背面，位置在背面的", emoji: "⬅️", image: "https://source.unsplash.com/featured/?back,behind", radical: "口", strokes: 6, isPictograph: false, words: ["后面", "前后", "后来", "然后"], sentences: ["我在你的后面。", "门后面有人。", "后来下雨了。"] },
        { char: "左", pinyin: "zuǒ", meaning: "面向南时靠东的一边（人的左手边）", emoji: "👈", image: "https://source.unsplash.com/featured/?left,direction", radical: "工", strokes: 5, isPictograph: false, words: ["左边", "左手", "左右", "向左"], sentences: ["左手拿书。", "左边有一棵树。", "向左转。"] },
        { char: "右", pinyin: "yòu", meaning: "面向南时靠西的一边（人的右手边）", emoji: "👉", image: "https://source.unsplash.com/featured/?right,direction", radical: "口", strokes: 5, isPictograph: false, words: ["右边", "右手", "左右", "向右"], sentences: ["右手拿笔。", "右边有一朵花。", "向右转。"] },
        { char: "东", pinyin: "dōng", meaning: "太阳出来的方向", emoji: "🌅", image: "https://source.unsplash.com/featured/?east,sunrise", radical: "一", strokes: 5, isPictograph: false, words: ["东方", "东边", "东西", "东风"], sentences: ["太阳从东方升起。", "东边有山。", "这是东风。"] },
        { char: "西", pinyin: "xī", meaning: "太阳落下去的方向", emoji: "🌇", image: "https://source.unsplash.com/featured/?west,sunset", radical: "覀", strokes: 6, isPictograph: false, words: ["西方", "西边", "东西", "西瓜"], sentences: ["太阳从西边落下。", "西边有河。", "西瓜很甜。"] },
        { char: "南", pinyin: "nán", meaning: "早上面向太阳时右手边的方向", emoji: "⬇️", image: "https://source.unsplash.com/featured/?south", radical: "十", strokes: 9, isPictograph: false, words: ["南方", "南边", "南北", "南风"], sentences: ["南方很热。", "南边有海。", "南风轻轻吹。"] },
        { char: "北", pinyin: "běi", meaning: "早上面向太阳时左手边的方向", emoji: "⬆️", image: "https://source.unsplash.com/featured/?north", radical: "匕", strokes: 5, isPictograph: false, words: ["北方", "北边", "南北", "北风"], sentences: ["北方很冷。", "北边有山。", "北风呼呼吹。"] }
    ],
    lesson10: [
        { char: "个", pinyin: "gè", meaning: "量词，用于没有专用量词的名词", emoji: "1️⃣", image: "https://source.unsplash.com/featured/?one,piece", radical: "人", strokes: 3, isPictograph: false, words: ["一个", "个人", "个子", "个别"], sentences: ["我有一个苹果。", "那个人是谁？", "他个子很高。"] },
        { char: "只", pinyin: "zhī", meaning: "量词，用于某些成对或单个的飞禽走兽等", emoji: "🐦", image: "https://source.unsplash.com/featured/?bird,one", radical: "口", strokes: 5, isPictograph: false, words: ["一只", "只有", "只是", "船只"], sentences: ["一只小鸟。", "只有一只。", "这只是我的。"] },
        { char: "朵", pinyin: "duǒ", meaning: "量词，用于花或云等", emoji: "🌸", image: "https://source.unsplash.com/featured/?flower,cloud", radical: "木", strokes: 6, isPictograph: false, words: ["一朵", "花朵", "云朵", "花骨朵"], sentences: ["一朵花。", "一朵白云。", "花朵真香。"] },
        { char: "条", pinyin: "tiáo", meaning: "量词，用于细长的东西或某些动物", emoji: "🐟", image: "https://source.unsplash.com/featured/?fish,long", radical: "木", strokes: 7, isPictograph: false, words: ["一条", "条件", "面条", "金鱼"], sentences: ["一条鱼。", "一条小路。", "妈妈煮面条。"] },
        { char: "位", pinyin: "wèi", meaning: "量词，用于人（含敬意）", emoji: "🧍", image: "https://source.unsplash.com/featured/?person,stand", radical: "亻", strokes: 7, isPictograph: false, words: ["一位", "位置", "座位", "各位"], sentences: ["一位老师。", "请坐在这个位置。", "各位好。"] },
        { char: "双", pinyin: "shuāng", meaning: "两个相配成对的", emoji: "👐", image: "https://source.unsplash.com/featured/?pair,hands", radical: "又", strokes: 4, isPictograph: false, words: ["一双", "双手", "双方", "双眼"], sentences: ["一双手。", "一双鞋。", "双手举起来。"] },
        { char: "把", pinyin: "bǎ", meaning: "量词，用于有把手的器具或一把抓住的东西", emoji: "🌂", image: "https://source.unsplash.com/featured/?hold,umbrella", radical: "扌", strokes: 7, isPictograph: false, words: ["一把", "把握", "把手", "扫把"], sentences: ["一把伞。", "一把椅子。", "抓住把手。"] },
        { char: "件", pinyin: "jiàn", meaning: "量词，用于衣服、事情等", emoji: "👕", image: "https://source.unsplash.com/featured/?clothes,thing", radical: "亻", strokes: 6, isPictograph: false, words: ["一件", "事情", "条件", "零件"], sentences: ["一件衣服。", "一件事。", "这是一件好事。"] }
    ]
};

// 课程信息
const chineseLessons = [
    { id: "lesson1", name: "第一课", title: "人与家", total: 8 },
    { id: "lesson2", name: "第二课", title: "天地日月", total: 8 },
    { id: "lesson3", name: "第三课", title: "山川田野", total: 8 },
    { id: "lesson4", name: "第四课", title: "动物身体", total: 8 },
    { id: "lesson5", name: "第五课", title: "人体自然", total: 8 },
    { id: "lesson6", name: "第六课", title: "植物天气", total: 8 },
    { id: "lesson7", name: "第七课", title: "常用动词", total: 8 },
    { id: "lesson8", name: "第八课", title: "学习用品", total: 8 },
    { id: "lesson9", name: "第九课", title: "方向位置", total: 8 },
    { id: "lesson10", name: "第十课", title: "常用量词", total: 8 }
];
